In [1]:
import pandas as pd

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [3]:
s=pd.Series([35,67,90,45])

def pass_fail(x):
    return 'PASS' if x>50 else 'FAIL'

result=s.apply(pass_fail)

In [4]:
result

0    FAIL
1    PASS
2    PASS
3    FAIL
dtype: object

In [24]:
df=pd.DataFrame({'Physics':[60,70,80],
                'Chemistry':[65,75,85],
                'Maths':[70,80,90]})

In [10]:
result=df.apply(sum)
result

Physics      210
Chemistry    225
Maths        240
dtype: int64

In [11]:
result=df.apply(sum,axis=1)
result

0    195
1    225
2    255
dtype: int64

In [12]:
result=df.apply(lambda x:x.mean())
result

Physics      70.0
Chemistry    75.0
Maths        80.0
dtype: float64

In [25]:
df['total']=df.apply(lambda x:x.sum(),axis=1)
df

   Physics  Chemistry  Maths  total
0       60         65     70    195
1       70         75     80    225
2       80         85     90    255

In [26]:
def grade(total):
    if total>=250:
        return 'A'
    elif total>=200:
        return 'B'
    else:
        return 'C'

In [28]:
df['grade']=df['total'].apply(grade)
df

   Physics  Chemistry  Maths  total grade
0       60         65     70    195     C
1       70         75     80    225     B
2       80         85     90    255     A

In [30]:
df=pd.DataFrame({'width':[1,2],
                'height':[3,4]})
df

   width  height
0      1       3
1      2       4

In [31]:
def get_stats(row):
    return [row['width']*row['height'],2*(row['width']+row['height'])]

In [36]:
df.apply(get_stats,axis=1,result_type='expand')

0     [3, 8]
1    [8, 12]
dtype: object

In [38]:
df.apply(get_stats,axis=1,result_type='reduce')

0     [3, 8]
1    [8, 12]
dtype: object

In [39]:
df.apply(get_stats,axis=1,result_type='broadcast')

   width  height
0      3       8
1      8      12

In [46]:
df=pd.DataFrame({'A':[1,2],'B':[10,20]})
df

   A   B
0  1  10
1  2  20

In [49]:
def add_values(x,y,z):
    return x+y+z
def add_values1(x,m):
    return x*m

In [48]:
df1=df.apply(add_values,args=(1,2))
df1

   A   B
0  4  13
1  5  23

In [51]:
df1=df.apply(add_values1,m=10)
df1

    A    B
0  10  100
1  20  200