In [1]:
import pandas as pd
import numpy as np

df=pd.read_csv('auto-mpg.csv')

df

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [7]:
df.head(3)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite

In [28]:
df[df["horsepower"]=='?']

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
32,25.0,4,98.0,?,2046,19.0,71,1,ford pinto
126,21.0,6,200.0,?,2875,17.0,74,1,ford maverick
330,40.9,4,85.0,?,1835,17.3,80,2,renault lecar deluxe
336,23.6,4,140.0,?,2905,14.3,80,1,ford mustang cobra
354,34.5,4,100.0,?,2320,15.8,81,2,renault 18i
374,23.0,4,151.0,?,3035,20.5,82,1,amc concord dl

In [27]:
df[df["horsepower"]=='?'].shape[0]

6

In [29]:
df.describe()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [33]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [64]:
import pandas as pd
import numpy as np

df=pd.read_csv('auto-mpg1.csv')

df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504.0,12.0,70.0,1.0,chevrolet chevelle malibu
1,15.0,8,NaN,165,3693.0,11.5,70.0,1.0,buick skylark 320
2,18.0,8,318.0,150,3436.0,11.0,NaN,1.0,plymouth satellite
3,16.0,8,304.0,150,3433.0,12.0,70.0,1.0,amc rebel sst
4,17.0,8,302.0,140,3449.0,10.5,70.0,1.0,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,NaN,15.6,82.0,1.0,ford mustang gl
394,44.0,4,NaN,52,2130.0,24.6,82.0,2.0,vw pickup
395,32.0,4,135.0,84,2295.0,11.6,82.0,1.0,dodge rampage
396,28.0,4,120.0,79,2625.0,18.6,82.0,1.0,ford ranger
397,31.0,4,119.0,82,2720.0,19.4,82.0,1.0,chevy s-10

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           397 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  388 non-null    float64
 3   horsepower    395 non-null    object
 4   weight        396 non-null    float64
 5   acceleration  398 non-null    float64
 6   model year    395 non-null    float64
 7   origin        397 non-null    float64
 8   car name      397 non-null    object
dtypes: float64(6), int64(1), object(2)
memory usage: 28.1+ KB

In [66]:
df.isna().sum()

mpg              1
cylinders        0
displacement    10
horsepower       3
weight           2
acceleration     0
model year       3
origin           1
car name         1
dtype: int64

In [67]:
df.isnull()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,False,False,False,False,False,False,False,False,False
1,False,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
393,False,False,False,False,True,False,False,False,False
394,False,False,True,False,False,False,False,False,False
395,False,False,False,False,False,False,False,False,False
396,False,False,False,False,False,False,False,False,False
397,False,False,False,False,False,False,False,False,False

In [68]:
df[df["horsepower"].isnull()]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
21,24.0,4,107.0,NaN,2430.0,14.5,70.0,2.0,audi 100 ls
107,18.0,6,232.0,NaN,2789.0,15.0,73.0,1.0,amc gremlin
247,39.4,4,85.0,NaN,2070.0,18.6,78.0,3.0,datsun b210 gx

In [69]:
df.loc[5]

mpg                           15
cylinders                      8
displacement                 429
horsepower                   198
weight                      4341
acceleration                  10
model year                    70
origin                         1
car name        ford galaxie 500
Name: 5, dtype: object

In [70]:
df.loc[5:10]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
5,15.0,8,429.0,198,4341.0,10.0,70.0,1.0,ford galaxie 500
6,14.0,8,454.0,220,4354.0,9.0,70.0,1.0,chevrolet impala
7,14.0,8,440.0,215,4312.0,8.5,70.0,1.0,plymouth fury iii
8,14.0,8,455.0,225,4425.0,10.0,70.0,1.0,pontiac catalina
9,15.0,8,390.0,190,3850.0,8.5,70.0,1.0,amc ambassador dpl
10,15.0,8,383.0,170,3563.0,10.0,70.0,1.0,dodge challenger se

In [71]:
df['mpg']

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [72]:
df['mpg'].loc[5]

15.0

In [73]:
df.shape

(398, 9)

In [74]:
df.describe()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,397.000000,398.000000,388.000000,396.000000,398.000000,395.000000,397.00000
mean,23.520907,5.454774,191.643041,2973.204545,15.568090,76.035443,1.56927
std,7.824824,1.701004,103.019338,847.665713,2.757689,3.693699,0.79985
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.00000
25%,17.500000,4.000000,104.750000,2225.250000,13.825000,73.000000,1.00000
50%,23.000000,4.000000,146.000000,2811.000000,15.500000,76.000000,1.00000
75%,29.000000,8.000000,260.000000,3610.000000,17.175000,79.000000,2.00000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.00000

In [75]:
df.describe(include=[np.number])

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,397.000000,398.000000,388.000000,396.000000,398.000000,395.000000,397.00000
mean,23.520907,5.454774,191.643041,2973.204545,15.568090,76.035443,1.56927
std,7.824824,1.701004,103.019338,847.665713,2.757689,3.693699,0.79985
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.00000
25%,17.500000,4.000000,104.750000,2225.250000,13.825000,73.000000,1.00000
50%,23.000000,4.000000,146.000000,2811.000000,15.500000,76.000000,1.00000
75%,29.000000,8.000000,260.000000,3610.000000,17.175000,79.000000,2.00000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.00000

In [76]:
df.describe(exclude=[np.number])

       horsepower    car name
count         395         397
unique         94         304
top           150  ford pinto
freq           22           6

In [77]:
df['car name'].value_counts()

ford pinto             6
ford maverick          5
toyota corolla         5
amc matador            5
chevrolet impala       4
                      ..
plymouth horizon       1
chevrolet monza 2+2    1
volkswagen 411 (sw)    1
mercury marquis        1
toyota celica gt       1
Name: car name, Length: 304, dtype: int64

In [78]:
df.describe(include='all')

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
count,397.000000,398.000000,388.000000,395,396.000000,398.000000,395.000000,397.00000,397
unique,NaN,NaN,NaN,94,NaN,NaN,NaN,NaN,304
top,NaN,NaN,NaN,150,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,22,NaN,NaN,NaN,NaN,6
mean,23.520907,5.454774,191.643041,NaN,2973.204545,15.568090,76.035443,1.56927,NaN
std,7.824824,1.701004,103.019338,NaN,847.665713,2.757689,3.693699,0.79985,NaN
min,9.000000,3.000000,68.000000,NaN,1613.000000,8.000000,70.000000,1.00000,NaN
25%,17.500000,4.000000,104.750000,NaN,2225.250000,13.825000,73.000000,1.00000,NaN
50%,23.000000,4.000000,146.000000,NaN,2811.000000,15.500000,76.000000,1.00000,NaN
75%,29.000000,8.000000,260.000000,NaN,3610.000000,17.175000,79.000000,2.00000,NaN
max,46.600000,8.000000,455.000000,NaN,5140.000000,24.800000,82.000000,3.00000,NaN

In [80]:
df.describe(percentiles=[.30,.40,.60])

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,397.000000,398.000000,388.000000,396.000000,398.000000,395.000000,397.00000
mean,23.520907,5.454774,191.643041,2973.204545,15.568090,76.035443,1.56927
std,7.824824,1.701004,103.019338,847.665713,2.757689,3.693699,0.79985
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.00000
30%,18.000000,4.000000,112.000000,2305.000000,14.200000,73.000000,1.00000
40%,20.000000,4.000000,121.800000,2582.000000,14.800000,75.000000,1.00000
50%,23.000000,4.000000,146.000000,2811.000000,15.500000,76.000000,1.00000
60%,25.000000,6.000000,200.000000,3086.000000,16.000000,77.000000,1.00000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.00000

In [82]:
df[['mpg','cylinders']].describe()

              mpg   cylinders
count  397.000000  398.000000
mean    23.520907    5.454774
std      7.824824    1.701004
min      9.000000    3.000000
25%     17.500000    4.000000
50%     23.000000    4.000000
75%     29.000000    8.000000
max     46.600000    8.000000

In [83]:
df[0:10].describe()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,10.000000,10.0,9.000000,10.000000,10.000000,9.0,10.0
mean,15.600000,8.0,377.666667,3879.700000,10.300000,70.0,1.0
std,1.577621,0.0,69.088711,432.151735,1.337494,0.0,0.0
min,14.000000,8.0,302.000000,3433.000000,8.500000,70.0,1.0
25%,14.250000,8.0,307.000000,3462.750000,9.250000,70.0,1.0
50%,15.000000,8.0,390.000000,3771.500000,10.250000,70.0,1.0
75%,16.750000,8.0,440.000000,4333.750000,11.375000,70.0,1.0
max,18.000000,8.0,455.000000,4425.000000,12.000000,70.0,1.0

In [85]:
df.loc[0:9].describe()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,10.000000,10.0,9.000000,10.000000,10.000000,9.0,10.0
mean,15.600000,8.0,377.666667,3879.700000,10.300000,70.0,1.0
std,1.577621,0.0,69.088711,432.151735,1.337494,0.0,0.0
min,14.000000,8.0,302.000000,3433.000000,8.500000,70.0,1.0
25%,14.250000,8.0,307.000000,3462.750000,9.250000,70.0,1.0
50%,15.000000,8.0,390.000000,3771.500000,10.250000,70.0,1.0
75%,16.750000,8.0,440.000000,4333.750000,11.375000,70.0,1.0
max,18.000000,8.0,455.000000,4425.000000,12.000000,70.0,1.0

In [86]:
df.corr()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
mpg,1.000000,-0.775338,-0.802140,-0.831691,0.420909,0.577275,0.560765
cylinders,-0.775338,1.000000,0.949763,0.896251,-0.505419,-0.342408,-0.561466
displacement,-0.802140,0.949763,1.000000,0.932231,-0.532925,-0.344224,-0.605410
weight,-0.831691,0.896251,0.932231,1.000000,-0.416580,-0.300248,-0.578138
acceleration,0.420909,-0.505419,-0.532925,-0.416580,1.000000,0.280586,0.207308
model year,0.577275,-0.342408,-0.344224,-0.300248,0.280586,1.000000,0.174141
origin,0.560765,-0.561466,-0.605410,-0.578138,0.207308,0.174141,1.000000

In [2]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64