In [31]:
import pandas as pd

data={"calories":[420,380,390,400],"duration":[50,40,45,48]}

df=pd.DataFrame(data,index=['day1','day2','day3','day4'])

df

      calories  duration
day1       420        50
day2       380        40
day3       390        45
day4       400        48

In [32]:
df.loc['day1']

calories    420
duration     50
Name: day1, dtype: int64

In [33]:
df.loc['day2']

calories    380
duration     40
Name: day2, dtype: int64

In [34]:
df['duration']

day1    50
day2    40
day3    45
day4    48
Name: duration, dtype: int64

In [35]:
df['calories']

day1    420
day2    380
day3    390
day4    400
Name: calories, dtype: int64

In [36]:
df.loc[['day1','day2']]

      calories  duration
day1       420        50
day2       380        40

In [37]:
import pandas as pd

data={'name':['Alice','Bob','Charlie'],'age':[25,30,35],'city':['NY','LA','Chicago']}

df=pd.DataFrame(data)

In [38]:
df

      name  age     city
0    Alice   25       NY
1      Bob   30       LA
2  Charlie   35  Chicago

In [39]:
df.iloc[0]

name    Alice
age        25
city       NY
Name: 0, dtype: object

In [40]:
df.loc[0:1]

    name  age city
0  Alice   25   NY
1    Bob   30   LA

In [30]:
df.iloc[0:1]

      calories  duration
day1       420        50

In [41]:
df.loc[(df.age>26)]

      name  age     city
1      Bob   30       LA
2  Charlie   35  Chicago

In [43]:
df.loc[(df.age>26) & (df.city=='Chicago')]

      name  age     city
2  Charlie   35  Chicago

In [44]:
import pandas as pd

data={'A':[1,2,3,4],'B':[5,6,7,8]}

df=pd.DataFrame(data,index=['r1','r2','r3','r4'])

In [45]:
df

    A  B
r1  1  5
r2  2  6
r3  3  7
r4  4  8

In [47]:
df.loc['r2':'r4','B']=99
df

    A   B
r1  1   5
r2  2  99
r3  3  99
r4  4  99

In [49]:
df.iloc[0:2,0]=0
df

    A   B
r1  0   5
r2  0  99
r3  3  99
r4  4  99

In [53]:
df['C']=[10,20,30,40]
df

    A   B   C
r1  0   5  10
r2  0  99  20
r3  3  99  30
r4  4  99  40

In [56]:
df.loc[df['A']==0,'new_col']="Zero"
df

    A   B   C new_col
r1  0   5  10    Zero
r2  0  99  20    Zero
r3  3  99  30     NaN
r4  4  99  40     NaN

In [59]:
df.loc[len(df)]=[10,11,12,13]
df

     A   B   C new_col
r1   0   5  10    Zero
r2   0  99  20    Zero
r3   3  99  30     NaN
r4   4  99  40     NaN
4   10  11  12      13

In [75]:
import pandas as pd

data={'name':['Alice','Bob','Charlie'],'age':[25,30,35],'city':['NY','LA','Chicago']}

df=pd.DataFrame(data)

df

      name  age     city
0    Alice   25       NY
1      Bob   30       LA
2  Charlie   35  Chicago

In [74]:
df.set_index("name")

         age     city
name
Alice     25       NY
Bob       30       LA
Charlie   35  Chicago

In [68]:
df.set_index("name",drop=False)

            name  age     city
name
Alice      Alice   25       NY
Bob          Bob   30       LA
Charlie  Charlie   35  Chicago

In [76]:
df.set_index("name",drop=False,inplace=True)
df

            name  age     city
name
Alice      Alice   25       NY
Bob          Bob   30       LA
Charlie  Charlie   35  Chicago

In [10]:
import pandas as pd

data={'region':['North','North','South','South'],'city':['NY','LA','Miami','Houston'],'population':[8.4,3.4,0.4,2.3]}

df=pd.DataFrame(data,index=['a','b','c','d'])

df

  region     city  population
a  North       NY         8.4
b  North       LA         3.4
c  South    Miami         0.4
d  South  Houston         2.3

In [2]:
df.set_index(['region','city'],inplace=True)
df

                population
region city
North  NY              8.4
       LA              3.4
South  Miami           0.4
       Houston         2.3

In [3]:
df_reset=df.reset_index(drop=True)
df_reset

   population
0         8.4
1         3.4
2         0.4
3         2.3

In [11]:
df.columns

Index(['region', 'city', 'population'], dtype='object')

In [12]:
df.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [13]:
df.size

12

In [14]:
df.ndim

2

In [15]:
df.shape

(4, 3)

In [16]:
df.values

array([['North', 'NY', 8.4],
       ['North', 'LA', 3.4],
       ['South', 'Miami', 0.4],
       ['South', 'Houston', 2.3]], dtype=object)

In [19]:
df.sample()

  region city  population
b  North   LA         3.4

In [20]:
df.nunique()

region        2
city          4
population    4
dtype: int64

In [24]:
df["city"].unique()

array(['NY', 'LA', 'Miami', 'Houston'], dtype=object)

In [26]:
df["region"].unique()

array(['North', 'South'], dtype=object)