In [1]:
import pandas as pd
import numpy as np

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
sales_data=pd.DataFrame({'Name':["William","Emma","Sofia","Markus","Edward",'Thomas',"Ethan",np.nan,"Arun","Amika","Paulo"],
                        'Region':[np.nan,"North","East",np.nan,"West","West","South",np.nan,'West',"East","South"],
                        'Sales':[50000,52000,np.nan,np.nan,42000,72000,49000,np.nan,67000,65000,67000],
                        'expenses':[42000,43000,np.nan,np.nan,38000,39000,42000,np.nan,39000,50000,45000]})

In [3]:
sales_data

       Name Region    Sales  expenses
0   William    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
2     Sofia   East      NaN       NaN
3    Markus    NaN      NaN       NaN
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
7       NaN    NaN      NaN       NaN
8      Arun   West  67000.0   39000.0
9     Amika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

In [4]:
sales_data.isnull().sum()

Name        1
Region      3
Sales       3
expenses    3
dtype: int64

In [5]:
sales_data.dropna()

      Name Region    Sales  expenses
1     Emma  North  52000.0   43000.0
4   Edward   West  42000.0   38000.0
5   Thomas   West  72000.0   39000.0
6    Ethan  South  49000.0   42000.0
8     Arun   West  67000.0   39000.0
9    Amika   East  65000.0   50000.0
10   Paulo  South  67000.0   45000.0

In [6]:
sales_data.dropna(thresh=3)

       Name Region    Sales  expenses
0   William    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
8      Arun   West  67000.0   39000.0
9     Amika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

In [7]:
sales_data.dropna(how='any')

      Name Region    Sales  expenses
1     Emma  North  52000.0   43000.0
4   Edward   West  42000.0   38000.0
5   Thomas   West  72000.0   39000.0
6    Ethan  South  49000.0   42000.0
8     Arun   West  67000.0   39000.0
9    Amika   East  65000.0   50000.0
10   Paulo  South  67000.0   45000.0

In [8]:
sales_data.dropna(how='all')

       Name Region    Sales  expenses
0   William    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
2     Sofia   East      NaN       NaN
3    Markus    NaN      NaN       NaN
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
8      Arun   West  67000.0   39000.0
9     Amika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

In [9]:
sales_data.dropna(subset=['Sales','expenses'])

       Name Region    Sales  expenses
0   William    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
8      Arun   West  67000.0   39000.0
9     Amika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

In [10]:
sales_data.dropna(axis=0) # check rows

      Name Region    Sales  expenses
1     Emma  North  52000.0   43000.0
4   Edward   West  42000.0   38000.0
5   Thomas   West  72000.0   39000.0
6    Ethan  South  49000.0   42000.0
8     Arun   West  67000.0   39000.0
9    Amika   East  65000.0   50000.0
10   Paulo  South  67000.0   45000.0

In [11]:
sales_data.dropna(axis=1) # check columns

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [12]:
sales_data

       Name Region    Sales  expenses
0   William    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
2     Sofia   East      NaN       NaN
3    Markus    NaN      NaN       NaN
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
7       NaN    NaN      NaN       NaN
8      Arun   West  67000.0   39000.0
9     Amika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

In [13]:
sales_data.fillna(0)

       Name Region    Sales  expenses
0   William      0  50000.0   42000.0
1      Emma  North  52000.0   43000.0
2     Sofia   East      0.0       0.0
3    Markus      0      0.0       0.0
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
7         0      0      0.0       0.0
8      Arun   West  67000.0   39000.0
9     Amika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

In [14]:
sales_data['Name'].fillna('Guest')

0     William
1        Emma
2       Sofia
3      Markus
4      Edward
5      Thomas
6       Ethan
7       Guest
8        Arun
9       Amika
10      Paulo
Name: Name, dtype: object

In [15]:
sales_data['Sales'].fillna(sales_data['Sales'].mean())

0     50000.0
1     52000.0
2     58000.0
3     58000.0
4     42000.0
5     72000.0
6     49000.0
7     58000.0
8     67000.0
9     65000.0
10    67000.0
Name: Sales, dtype: float64

In [16]:
sales_data['Sales'].fillna(sales_data['Sales'].median())

0     50000.0
1     52000.0
2     58500.0
3     58500.0
4     42000.0
5     72000.0
6     49000.0
7     58500.0
8     67000.0
9     65000.0
10    67000.0
Name: Sales, dtype: float64

In [28]:
import pandas as pd
import numpy as np

df=pd.read_csv('auto-mpg.csv')

df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [18]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [19]:
df[df["horsepower"]=='?']

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
32,25.0,4,98.0,?,2046,19.0,71,1,ford pinto
126,21.0,6,200.0,?,2875,17.0,74,1,ford maverick
330,40.9,4,85.0,?,1835,17.3,80,2,renault lecar deluxe
336,23.6,4,140.0,?,2905,14.3,80,1,ford mustang cobra
354,34.5,4,100.0,?,2320,15.8,81,2,renault 18i
374,23.0,4,151.0,?,3035,20.5,82,1,amc concord dl

In [20]:
df[df["horsepower"]=='?']=np.nan

In [21]:
df['horsepower'].fillna('hp')

0      130
1      165
2      150
3      150
4      140
      ...
393     86
394     52
395     84
396     79
397     82
Name: horsepower, Length: 398, dtype: object

In [29]:
df=df[df['horsepower']!='?']
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 392 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    object
 4   weight        392 non-null    int64
 5   acceleration  392 non-null    float64
 6   model year    392 non-null    int64
 7   origin        392 non-null    int64
 8   car name      392 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 30.6+ KB

In [31]:
df["horsepower"]=df["horsepower"].astype('int64')

<ipython-input-31-109400a0d05e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["horsepower"]=df["horsepower"].astype('int64')

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 392 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    int64
 4   weight        392 non-null    int64
 5   acceleration  392 non-null    float64
 6   model year    392 non-null    int64
 7   origin        392 non-null    int64
 8   car name      392 non-null    object
dtypes: float64(3), int64(5), object(1)
memory usage: 30.6+ KB

In [33]:
df.drop('car name',axis=1)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin
0,18.0,8,307.0,130,3504,12.0,70,1
1,15.0,8,350.0,165,3693,11.5,70,1
2,18.0,8,318.0,150,3436,11.0,70,1
3,16.0,8,304.0,150,3433,12.0,70,1
4,17.0,8,302.0,140,3449,10.5,70,1
...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1
394,44.0,4,97.0,52,2130,24.6,82,2
395,32.0,4,135.0,84,2295,11.6,82,1
396,28.0,4,120.0,79,2625,18.6,82,1
397,31.0,4,119.0,82,2720,19.4,82,1