In [16]:
import pandas as pd

In [2]:
df=pd.DataFrame({
    'Product Category':['Electronics','Furniture','Electronics','Furniture'],
    'sales':[200,150,300,100]
})
df

  Product Category  sales
0      Electronics    200
1        Furniture    150
2      Electronics    300
3        Furniture    100

In [18]:
result=df.groupby('Product Category',axis=0,as_index=True,sort=True)['sales'].count()
result

Product Category
Electronics    2
Furniture      2
Name: sales, dtype: int64

In [19]:
result=df.groupby('Product Category',axis=0,as_index=False,sort=True)['sales'].count()
result

  Product Category  sales
0      Electronics      2
1        Furniture      2

In [21]:
df=pd.DataFrame({'Region':['East','East','West','West','East','West'],
                'Sales':[100,150,200,120,110,130],
                'Manager':['A','B','C','D','E','F']})
df

  Region  Sales Manager
0   East    100       A
1   East    150       B
2   West    200       C
3   West    120       D
4   East    110       E
5   West    130       F

In [24]:
def sales_range(group):
    return group['Sales'].max() - group['Sales'].min()
sales_data=df.groupby('Region').apply(sales_range)
print(sales_data)

Region
East    50
West    80
dtype: int64

In [28]:
df=pd.DataFrame({'dept':['Sales','Sales','HR','HR','IT','IT'],
                'Salary':[50000,60000,40000,45000,70000,75000],
                'Bonus':[5000,6000,2000,2500,8000,8500]})
df

    dept  Salary  Bonus
0  Sales   50000   5000
1  Sales   60000   6000
2     HR   40000   2000
3     HR   45000   2500
4     IT   70000   8000
5     IT   75000   8500

In [36]:
result=df.groupby('dept').agg('mean')
result

        Salary   Bonus
dept
HR     42500.0  2250.0
IT     72500.0  8250.0
Sales  55000.0  5500.0

In [39]:
result=df.groupby('dept').agg(['mean','median','max'])
result

        Salary                   Bonus
          mean   median    max    mean  median   max
dept
HR     42500.0  42500.0  45000  2250.0  2250.0  2500
IT     72500.0  72500.0  75000  8250.0  8250.0  8500
Sales  55000.0  55000.0  60000  5500.0  5500.0  6000

In [40]:
result=df.groupby('dept').agg({'Salary':['mean','max'],'Bonus':'sum'})
result

        Salary         Bonus
          mean    max    sum
dept
HR     42500.0  45000   4500
IT     72500.0  75000  16500
Sales  55000.0  60000  11000

In [42]:
result=df.groupby('dept').agg(MeanSalary=('Salary','mean'),MaxSalary=('Salary','max'),TotalBonus=('Bonus','sum'))
result

       MeanSalary  MaxSalary  TotalBonus
dept
HR        42500.0      45000        4500
IT        72500.0      75000       16500
Sales     55000.0      60000       11000