In [12]:
import pandas as pd

In [4]:
df1=pd.DataFrame({'employee':['A','B','C'],
                 'dept':['IT','HR','Finance']})
df2=pd.DataFrame({'employee':['A','B','D'],
                 'salary':[50000,40000,30000]})

In [5]:
result=pd.merge(df1,df2,on='employee')
result

  employee dept  salary
0        A   IT   50000
1        B   HR   40000

In [11]:
result=pd.merge(df1,df2,on='employee',how='right')
result

  employee dept  salary
0        A   IT   50000
1        B   HR   40000
2        D  NaN   30000

In [16]:
df1=pd.DataFrame({'emp_id':[101,102,103],
                 'name':['Amit','Riya','John'],
                 'salary':[50000,60000,55000]})
df2=pd.DataFrame({'emp_id':[101,102,103],
                  'name':['Amit','Riya','David'],
                 'salary':[52000,62000,58000]})

In [18]:
result=pd.merge(df1,df2,on='emp_id',suffixes=('_left','_right'))
result

   emp_id name_left  salary_left name_right  salary_right
0     101      Amit        50000       Amit         52000
1     102      Riya        60000       Riya         62000
2     103      John        55000      David         58000

In [23]:
df1=pd.DataFrame({'emp_id':[101,102,103],
                 'salary':[50000,60000,55000]})
df2=pd.DataFrame({'id':[101,102,103],
                 'salary':[52000,62000,58000]})

In [25]:
result=pd.merge(df1,df2,left_on='emp_id',right_on='id')
result

   emp_id  salary_x   id  salary_y
0     101     50000  101     52000
1     102     60000  102     62000
2     103     55000  103     58000

In [36]:
df1=pd.DataFrame({'Physics':[60,70,80],
                  's_id':[101,102,103]})
df2=pd.DataFrame({'name':['Amit','Riya','David']},
                  index=[101,102,103])

In [37]:
result=pd.merge(df1,df2,left_on='s_id',right_index=True)
result

   Physics  s_id   name
0       60   101   Amit
1       70   102   Riya
2       80   103  David