In [1]:
import pandas as pd

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [4]:
data={'A':['TeamA','TeamB','TeamB','TeamC','TeamA'],
     'B':[50,40,40,30,50],
     'C':[True,False,False,False,True]}
df=pd.DataFrame(data)
df

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
2  TeamB  40  False
3  TeamC  30  False
4  TeamA  50   True

In [8]:
df.duplicated(keep='first')

0     True
1     True
2     True
3    False
4     True
dtype: bool

In [11]:
df.duplicated(keep='last')

0     True
1     True
2    False
3    False
4    False
dtype: bool

In [10]:
df.duplicated(keep=False)

0     True
1     True
2     True
3    False
4     True
dtype: bool

In [12]:
df.drop_duplicates()

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
3  TeamC  30  False

In [14]:
df.drop_duplicates(inplace=True)
df

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
3  TeamC  30  False

In [15]:
df=df.reset_index(drop=True)
df

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
2  TeamC  30  False