In [1]:
import pandas as pd

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [3]:
df=pd.DataFrame({'marks':[80,85,0,90],
                'attendence':[75,80,0,85],
                'grade':['A','B','F','A']})
df

   marks  attendence grade
0     80          75     A
1     85          80     B
2      0           0     F
3     90          85     A

In [4]:
result=df.replace(0,60)
result

   marks  attendence grade
0     80          75     A
1     85          80     B
2     60          60     F
3     90          85     A

In [5]:
result=df.replace([80,75],[90,80])
result

   marks  attendence grade
0     90          80     A
1     85          90     B
2      0           0     F
3     90          85     A