In [1]:
import pandas as pd

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [25]:
df=pd.DataFrame({'name':['Alice','Bob','Charlie','David'],
                'score':[88,92,85,90]})
df

      name  score
0    Alice     88
1      Bob     92
2  Charlie     85
3    David     90

In [16]:
sorted_df=df.sort_values(by='score',ascending=False)
sorted_df

      name  score
1      Bob     92
3    David     90
0    Alice     88
2  Charlie     85

In [17]:
df

      name  score
0    Alice     88
1      Bob     92
2  Charlie     85
3    David     90

In [22]:
df.sort_index(ascending=False)

         score
name
David       90
Charlie     85
Bob         92
Alice       88

In [23]:
df

         score
name
Alice       88
Bob         92
Charlie     85
David       90

In [26]:
df.set_index('name',inplace=True)
df

         score
name
Alice       88
Bob         92
Charlie     85
David       90